services:
  postgres:
    image: postgres:17.5-alpine
    container_name: full-stack-blog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5433:5432"
  mailpit:
    image: axllent/mailpit
    container_name: full-stack-blog-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"